export default [
    {
        name:'Overview',
        iconType:'Material',
        iconName:'view-dashboard'
    },
    {
        name:'Overview',
        iconType:'Material',
        iconName:'view-dashboard'
        /*name:'Transactions',
        iconType:'Feather',
        iconName:'settings'*/
    },
    {
        name:'Wallet',
        iconType:'Material',
        iconName:'view-dashboard'
    },
    {
        name:'Overview',
        iconType:'Material',
        iconName:'view-dashboard'
        /*name:'Analytics',
        iconType:'FontAwesome5',
        iconName:'user-friends'*/
    },
    {
        name:'Investments',
        iconType:'Material',
        iconName:'view-dashboard'
    },
    {
        name:'Debts',
        iconType:'Material',
        iconName:'view-dashboard'
    },
    {
        name:'Crypto',
        iconType:'Material',
        iconName:'view-dashboard'
    }
]