# Generated by Django 4.1.3 on 2022-11-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_id_alter_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='company',
            new_name='ticker',
        ),
    ]
