# Generated by Django 4.1.3 on 2022-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_company_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='current_amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
