# Generated by Django 4.1.3 on 2022-12-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_stock_created_at_delete_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
    ]
