# Generated by Django 4.1.3 on 2022-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_wallet_is_debt_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
