# Generated by Django 4.1.3 on 2022-11-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='description',
        ),
    ]
