# Generated by Django 4.1.3 on 2022-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_wallet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='icon',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
