# Generated by Django 4.1.3 on 2022-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_transaction_amount_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
