# Generated by Django 4.1.3 on 2022-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_wallet_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='currency',
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='income',
            field=models.BooleanField(null=True),
        ),
    ]
