# Generated by Django 4.1.3 on 2022-12-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0001_initial'),
        ('wallets', '0008_remove_transactioncategory_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_amount',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_amount',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='color',
            field=models.ForeignKey(default='#000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='decorations.color'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('source_amount__gt', 0)), name='transaction_source_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('target_amount__gt', 0)), name='transaction_target_amount_positive'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
