# Generated by Django 4.1.3 on 2022-12-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0001_initial'),
        ('wallets', '0009_remove_transactiontype_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decorations.color'),
        ),
    ]
