# Generated by Django 4.1.3 on 2022-12-05 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_alter_transactioncategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
