# Generated by Django 4.1.3 on 2022-12-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_transactioncategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_wallet_transactions', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_wallet_transactions', to='wallets.wallet'),
        ),
    ]
