# Generated by Django 4.1.3 on 2022-12-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_walletlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet'),
        ),
    ]
