# Generated by Django 4.1.3 on 2022-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_rename_public_key_ethkeys_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethkeys',
            name='private_key',
            field=models.CharField(max_length=256),
        ),
    ]
