# Generated by Django 4.1.3 on 2022-12-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_ethkeys_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ethkeys',
            table='crypto_ethkeys',
        ),
    ]
