# Generated by Django 4.1.3 on 2022-11-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=32)),
                ('week_start', models.IntegerField(default=0)),
                ('start_page', models.CharField(default='dashboard', max_length=32)),
                ('main_currency', models.ForeignKey(default='USD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.currency')),
            ],
        ),
    ]
