# Generated by Django 4.1.3 on 2022-12-16 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0014_walletlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('chart_name', models.CharField(default=None, max_length=32, null=True)),
                ('chart_period', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=32)),
                ('week_start', models.IntegerField(default=0)),
                ('start_page', models.CharField(default='dashboard', max_length=32)),
                ('main_currency', models.ForeignKey(default='USD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.currency')),
            ],
        ),
    ]
