# Generated by Django 4.1.3 on 2022-11-23 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('chart_name', models.CharField(default=None, max_length=32, null=True)),
                ('chart_period', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
    ]
