# Generated by Django 4.1.3 on 2022-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_startpage_delete_chartsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='currency_format',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='date_format',
            field=models.CharField(default='dd LLLL yyyy', max_length=32),
        ),
    ]
