# Generated by Django 4.1.3 on 2022-12-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountsettings_currency_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='start_page',
            field=models.ForeignKey(default='Overview', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.startpage'),
        ),
    ]
