# Generated by Django 4.1.3 on 2022-11-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsindustry',
            old_name='industry',
            new_name='name',
        ),
    ]
