# Generated by Django 4.1.3 on 2022-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_ticker_remove_stock_color_remove_stock_description_and_more'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfilter',
            name='tickers',
        ),
        migrations.AddField(
            model_name='newsfilter',
            name='tickers',
            field=models.ManyToManyField(blank=True, db_table='news_filter_tickers', related_name='news_filters', to='investments.ticker'),
        ),
    ]
