# Generated by Django 4.1.3 on 2022-11-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_industry_newsindustry_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfilter',
            old_name='symbols',
            new_name='tickers',
        ),
    ]
