# Generated by Django 4.1.3 on 2022-12-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_symbols_newsfilter_tickers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLanguage',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsfilter',
            name='industries',
        ),
        migrations.DeleteModel(
            name='NewsIndustry',
        ),
        migrations.AddField(
            model_name='newsfilter',
            name='languages',
            field=models.ManyToManyField(blank=True, db_table='news_filter_languages', to='news.newslanguage'),
        ),
    ]
