# Generated by Django 4.1.3 on 2022-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newslanguage_remove_newsfilter_industries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslanguage',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
