create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to admin;

create table decorations_color
(
    hex_code varchar(7) not null
        primary key
);

alter table decorations_color
    owner to admin;

create index decorations_color_hex_code_963009f7_like
    on decorations_color (hex_code varchar_pattern_ops);

create table decorations_icon
(
    code varchar(32) not null
        primary key
);

alter table decorations_icon
    owner to admin;

create index decorations_icon_code_8f026099_like
    on decorations_icon (code varchar_pattern_ops);

create table wallets_currency
(
    code varchar(10) not null
        primary key,
    name varchar(64) not null
);

alter table wallets_currency
    owner to admin;

create index wallets_currency_code_2892e9ae_like
    on wallets_currency (code varchar_pattern_ops);

create table wallets_wallet
(
    id           uuid                     not null
        primary key,
    user_id      varchar(64)              not null,
    balance      numeric(30, 10)          not null,
    name         varchar(128)             not null,
    goal         numeric(30, 10),
    color_id     varchar(7)               not null
        constraint wallets_wallet_color_id_4faf01ec_fk_decorations_color_hex_code
            references decorations_color
            on delete cascade
            deferrable initially deferred,
    currency_id  varchar(10)
        constraint wallets_wallet_currency_id_4181fde6_fk_wallets_currency_code
            references wallets_currency
            on delete cascade
            deferrable initially deferred,
    last_updated timestamp with time zone not null,
    description  text                     not null
);

alter table wallets_wallet
    owner to admin;

create index wallets_wallet_user_id_6cb307a0
    on wallets_wallet (user_id);

create index wallets_wallet_user_id_6cb307a0_like
    on wallets_wallet (user_id varchar_pattern_ops);

create index wallets_wallet_color_id_4faf01ec
    on wallets_wallet (color_id);

create index wallets_wallet_color_id_4faf01ec_like
    on wallets_wallet (color_id varchar_pattern_ops);

create index wallets_wallet_currency_id_4181fde6
    on wallets_wallet (currency_id);

create index wallets_wallet_currency_id_4181fde6_like
    on wallets_wallet (currency_id varchar_pattern_ops);

create table wallets_transactioncategory
(
    id         uuid                     not null
        primary key,
    user_id    varchar(64)              not null,
    name       varchar(128)             not null,
    color_id   varchar(7)
        constraint wallets_transactionc_color_id_c8912b30_fk_decoratio
            references decorations_color
            on delete cascade
            deferrable initially deferred,
    icon_id    varchar(32)
        constraint wallets_transactionc_icon_id_3ef9f257_fk_decoratio
            references decorations_icon
            on delete cascade
            deferrable initially deferred,
    created_at timestamp with time zone not null
);

alter table wallets_transactioncategory
    owner to admin;

create index wallets_transactioncategory_user_id_35fdc9df
    on wallets_transactioncategory (user_id);

create index wallets_transactioncategory_user_id_35fdc9df_like
    on wallets_transactioncategory (user_id varchar_pattern_ops);

create index wallets_transactioncategory_color_id_c8912b30
    on wallets_transactioncategory (color_id);

create index wallets_transactioncategory_color_id_c8912b30_like
    on wallets_transactioncategory (color_id varchar_pattern_ops);

create index wallets_transactioncategory_icon_id_3ef9f257
    on wallets_transactioncategory (icon_id);

create index wallets_transactioncategory_icon_id_3ef9f257_like
    on wallets_transactioncategory (icon_id varchar_pattern_ops);

create table wallets_transaction
(
    id               uuid                     not null
        primary key,
    user_id          varchar(64)              not null,
    description      varchar(256),
    created_at       timestamp with time zone not null,
    category_id      uuid
        constraint wallets_transaction_category_id_f7f666fd_fk_wallets_t
            references wallets_transactioncategory
            on delete cascade
            deferrable initially deferred,
    source_wallet_id uuid
        constraint wallets_transaction_source_wallet_id_7abc2933_fk_wallets_w
            references wallets_wallet
            on delete cascade
            deferrable initially deferred,
    target_wallet_id uuid
        constraint wallets_transaction_target_wallet_id_8e941cae_fk_wallets_w
            references wallets_wallet
            on delete cascade
            deferrable initially deferred,
    source_amount    numeric(30, 10)
        constraint transaction_source_amount_positive
            check (source_amount > (0)::numeric),
    target_amount    numeric(30, 10)
        constraint transaction_target_amount_positive
            check (target_amount > (0)::numeric)
);

alter table wallets_transaction
    owner to admin;

create index wallets_transaction_user_id_d1e467fd
    on wallets_transaction (user_id);

create index wallets_transaction_user_id_d1e467fd_like
    on wallets_transaction (user_id varchar_pattern_ops);

create index wallets_transaction_category_id_f7f666fd
    on wallets_transaction (category_id);

create index wallets_transaction_source_wallet_id_7abc2933
    on wallets_transaction (source_wallet_id);

create index wallets_transaction_target_wallet_id_8e941cae
    on wallets_transaction (target_wallet_id);

create table wallets_debt
(
    id         uuid        not null
        primary key,
    user_id    varchar(64) not null,
    expires_at date        not null,
    wallet_id  uuid        not null
        constraint wallets_debt_wallet_id_39721d2f_uniq
            unique
        constraint wallets_debt_wallet_id_39721d2f_fk_wallets_wallet_id
            references wallets_wallet
            on delete cascade
            deferrable initially deferred
);

alter table wallets_debt
    owner to admin;

create index wallets_debt_user_id_ddc1b794
    on wallets_debt (user_id);

create index wallets_debt_user_id_ddc1b794_like
    on wallets_debt (user_id varchar_pattern_ops);

create table wallets_walletlog
(
    id        uuid            not null
        primary key,
    balance   numeric(30, 10) not null,
    currency  varchar(10)     not null,
    date      date            not null,
    wallet_id uuid            not null
        constraint wallets_walletlog_wallet_id_4599341b_fk_wallets_wallet_id
            references wallets_wallet
            on delete cascade
            deferrable initially deferred
);

alter table wallets_walletlog
    owner to admin;

create index wallets_walletlog_wallet_id_4599341b
    on wallets_walletlog (wallet_id);

create table accounts_startpage
(
    name varchar(32) not null
        primary key
);

alter table accounts_startpage
    owner to admin;

create table accounts_accountsettings
(
    id               uuid        not null
        primary key,
    user_id          varchar(64) not null
        unique,
    date_format      varchar(32) not null,
    start_page_id    varchar(32) not null
        constraint accounts_accountsett_start_page_id_88c1ca8c_fk_accounts_
            references accounts_startpage
            on delete cascade
            deferrable initially deferred,
    main_currency_id varchar(10) not null
        constraint accounts_accountsett_main_currency_id_26f90127_fk_wallets_c
            references wallets_currency
            on delete cascade
            deferrable initially deferred,
    currency_format  varchar(5)  not null
);

alter table accounts_accountsettings
    owner to admin;

create index accounts_accountsettings_user_id_d7ae1585_like
    on accounts_accountsettings (user_id varchar_pattern_ops);

create index accounts_accountsettings_main_currency_id_26f90127
    on accounts_accountsettings (main_currency_id);

create index accounts_accountsettings_main_currency_id_26f90127_like
    on accounts_accountsettings (main_currency_id varchar_pattern_ops);

create index accounts_accountsettings_start_page_id_88c1ca8c
    on accounts_accountsettings (start_page_id);

create index accounts_accountsettings_start_page_id_88c1ca8c_like
    on accounts_accountsettings (start_page_id varchar_pattern_ops);

create index accounts_startpage_name_a7d6768c_like
    on accounts_startpage (name varchar_pattern_ops);

create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to admin;

create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to admin;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table auth_group
    owner to admin;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table auth_group_permissions
    owner to admin;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

create table auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table auth_user
    owner to admin;

create index auth_user_username_6821ab7c_like
    on auth_user (username varchar_pattern_ops);

create table auth_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  integer not null
        constraint auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups_group_id_97559544_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint auth_user_groups_user_id_group_id_94350c0c_uniq
        unique (user_id, group_id)
);

alter table auth_user_groups
    owner to admin;

create index auth_user_groups_user_id_6a12ed8b
    on auth_user_groups (user_id);

create index auth_user_groups_group_id_97559544
    on auth_user_groups (group_id);

create table auth_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       integer not null
        constraint auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        unique (user_id, permission_id)
);

alter table auth_user_user_permissions
    owner to admin;

create index auth_user_user_permissions_user_id_a95ead1b
    on auth_user_user_permissions (user_id);

create index auth_user_user_permissions_permission_id_1fbb5f2c
    on auth_user_user_permissions (permission_id);

create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint django_admin_log_user_id_c564eba6_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to admin;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create table blacklist_blacklistedtoken
(
    id             integer generated by default as identity
        primary key,
    token          text,
    expires_at     timestamp with time zone not null,
    blacklisted_at timestamp with time zone not null,
    user_id        integer                  not null
        constraint blacklist_blacklistedtoken_user_id_e4068fb1_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    token_id       uuid,
    constraint token_or_id_not_null
        check ((token_id IS NOT NULL) OR (token IS NOT NULL))
);

alter table blacklist_blacklistedtoken
    owner to admin;

create index blacklist_blacklistedtoken_token_acbfdd7e
    on blacklist_blacklistedtoken (token);

create index blacklist_blacklistedtoken_token_acbfdd7e_like
    on blacklist_blacklistedtoken (token text_pattern_ops);

create index blacklist_blacklistedtoken_expires_at_8ffda1c1
    on blacklist_blacklistedtoken (expires_at);

create index blacklist_blacklistedtoken_user_id_e4068fb1
    on blacklist_blacklistedtoken (user_id);

create index blacklist_blacklistedtoken_token_id_aee3ed90
    on blacklist_blacklistedtoken (token_id);

create table crypto_ethkeys
(
    id          uuid         not null
        primary key,
    user_id     varchar(64)  not null,
    private_key varchar(256) not null,
    address     varchar(128) not null
        constraint crypto_ethkeys_address_4c5394a1_uniq
            unique
);

alter table crypto_ethkeys
    owner to admin;

create index crypto_ethkeys_user_id_cd97a592
    on crypto_ethkeys (user_id);

create index crypto_ethkeys_user_id_cd97a592_like
    on crypto_ethkeys (user_id varchar_pattern_ops);

create index crypto_ethkeys_address_4c5394a1_like
    on crypto_ethkeys (address varchar_pattern_ops);

create table investments_ticker
(
    code varchar(10) not null
        primary key
);

alter table investments_ticker
    owner to admin;

create table investments_stock
(
    id         uuid                     not null
        primary key,
    user_id    varchar(64)              not null,
    amount     numeric(30, 10)          not null,
    ticker_id  varchar(10)
        constraint investments_stock_ticker_id_4820cd55_fk_investments_ticker_code
            references investments_ticker
            on delete cascade
            deferrable initially deferred,
    created_at timestamp with time zone not null
);

alter table investments_stock
    owner to admin;

create index investments_stock_user_id_40a28db2
    on investments_stock (user_id);

create index investments_stock_user_id_40a28db2_like
    on investments_stock (user_id varchar_pattern_ops);

create index investments_stock_ticker_id_4820cd55
    on investments_stock (ticker_id);

create index investments_stock_ticker_id_4820cd55_like
    on investments_stock (ticker_id varchar_pattern_ops);

create index investments_ticker_code_06ba5f70_like
    on investments_ticker (code varchar_pattern_ops);

create table investments_investment
(
    id         uuid                     not null
        primary key,
    user_id    varchar(64)              not null,
    percent    numeric(30, 10)          not null,
    created_at timestamp with time zone not null,
    wallet_id  uuid                     not null
        unique
        constraint investments_investment_wallet_id_fd9b92b1_fk_wallets_wallet_id
            references wallets_wallet
            on delete cascade
            deferrable initially deferred
);

alter table investments_investment
    owner to admin;

create index investments_investment_user_id_0e0ca19d
    on investments_investment (user_id);

create index investments_investment_user_id_0e0ca19d_like
    on investments_investment (user_id varchar_pattern_ops);

create table news_newslanguage
(
    code varchar(5) not null
        primary key
);

alter table news_newslanguage
    owner to admin;

create index news_newslanguage_code_61269370_like
    on news_newslanguage (code varchar_pattern_ops);

create table news_newsfilter
(
    id      uuid        not null
        primary key,
    user_id varchar(64) not null
        unique
);

alter table news_newsfilter
    owner to admin;

create index news_newsfilter_user_id_fa208b2f_like
    on news_newsfilter (user_id varchar_pattern_ops);

create table news_filter_languages
(
    id              bigint generated by default as identity
        primary key,
    newsfilter_id   uuid       not null
        constraint news_filter_language_newsfilter_id_f6fabad9_fk_news_news
            references news_newsfilter
            on delete cascade
            deferrable initially deferred,
    newslanguage_id varchar(5) not null
        constraint news_filter_language_newslanguage_id_4971ae7d_fk_news_news
            references news_newslanguage
            on delete cascade
            deferrable initially deferred,
    constraint news_filter_languages_newsfilter_id_newslangua_de34eabe_uniq
        unique (newsfilter_id, newslanguage_id)
);

alter table news_filter_languages
    owner to admin;

create index news_filter_languages_newsfilter_id_f6fabad9
    on news_filter_languages (newsfilter_id);

create index news_filter_languages_newslanguage_id_4971ae7d
    on news_filter_languages (newslanguage_id);

create index news_filter_languages_newslanguage_id_4971ae7d_like
    on news_filter_languages (newslanguage_id varchar_pattern_ops);

create table news_filter_tickers
(
    id            bigint generated by default as identity
        primary key,
    newsfilter_id uuid        not null
        constraint news_filter_tickers_newsfilter_id_082a9638_fk_news_news
            references news_newsfilter
            on delete cascade
            deferrable initially deferred,
    ticker_id     varchar(10) not null
        constraint news_filter_tickers_ticker_id_c0da232c_fk_investmen
            references investments_ticker
            on delete cascade
            deferrable initially deferred,
    constraint news_filter_tickers_newsfilter_id_ticker_id_78a1f6e0_uniq
        unique (newsfilter_id, ticker_id)
);

alter table news_filter_tickers
    owner to admin;

create index news_filter_tickers_newsfilter_id_082a9638
    on news_filter_tickers (newsfilter_id);

create index news_filter_tickers_ticker_id_c0da232c
    on news_filter_tickers (ticker_id);

create index news_filter_tickers_ticker_id_c0da232c_like
    on news_filter_tickers (ticker_id varchar_pattern_ops);

create table django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to admin;

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

